### ISSUE TITLE
大佬能否加入多账号自动获取ck

### ISSUE THREAD

**Issue by uwhatsup** [zgcwkjOpenProject/Android_GetCookies#1]
保存多个账号在软件配置里，然后可以读取青龙的ck是否失效，失效了就登录并更新ck

可以参考一下这个项目
https://github.com/icepage/AutoUpdateJdCookie

通过青龙的 client_id和client_secret 就可以获取到ck

**Comment by zgcwkj** [comment]
这，得关联青龙了。。。莫得动力呀~

**Comment by uwhatsup** [comment]
post一下就搞掂

**Comment by zgcwkj** [comment]
> post一下就搞掂


要不你直接告诉我地址？🤔

**Comment by uwhatsup** [comment]
可以参考一下这个文档 https://github.com/icepage/AutoUpdateJdCookie/blob/main/api/qinglong.py


post地址就是这样 http://127.0.0.1/open/envs/disable  


OpenApi使用指南

在系统设置 -> 应用设置 -> 添加应用，权限目前支持5个模块，可以选择多个模块。选择一个模块之后，可读写此模块的所有接口。
使用生成的 client_id 和 client_secret 请求获取token接口 http://localhost:5700/open/auth/token?client_id=xxxxxx&client_secret=xxxxxxxx
上面接口返回的token有效期为30天，可用于请求青龙的接口 curl 'http://localhost:5700/open/envs?searchValue=&t=1630032278171' -H 'Authorization: Bearer 接口返回的token'
openapi的接口与系统正常接口的区别就是青龙里的是/api/envs，openapi是/open/envs，即就是青龙接口中的api换成open

**Comment by zgcwkj** [comment]
@uwhatsup 青龙的可以了。多个账号这个弄不出来，webview 我没找到不共享cookie的方法。

没别的问题，我晚些时候**关闭此 issues** （逃 😬

**Comment by uwhatsup** [comment]
是否可以隐私模式  登录的时候选择对应的账号，登录完一个账号就关闭软件  再重新打开

**Comment by zgcwkj** [comment]
@uwhatsup 这种没用，每次都要输信息，更麻烦。

**Comment by uwhatsup** [comment]
好的，那暂时先这样了，谢谢大佬

**Comment by zgcwkj** [comment]
最新提交已经支持：https://github.com/zgcwkjOpenProject/Android_GetCookies/commit/72cfe62af12d896fa869be54e4d10081b60e6c74
